const fs = require('fs');
const path = require('path');
const os = require('os');
const archiver = require('archiver');
const PDFDocument = require('pdfkit');
const pptxgen = require('pptxgenjs');
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');
const ExcelJS = require('exceljs');

function safeName(name) {
  return String(name || 'kelnara-output')
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'kelnara-output';
}

function makeWorkDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'kelnara-'));
  return dir;
}

function zipFolder(sourceDir, outPath) {
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(outPath);
    const archive = archiver('zip', { zlib: { level: 9 } });
    output.on('close', () => resolve(outPath));
    archive.on('error', reject);
    archive.pipe(output);
    archive.directory(sourceDir, false);
    archive.finalize();
  });
}

function detectArtifactType(prompt) {
  const p = String(prompt || '').toLowerCase();
  if (/(ppt|powerpoint|presentasi|slide)/i.test(p)) return 'pptx';
  if (/(pdf|poster|laporan pdf|dokumen pdf)/i.test(p)) return 'pdf';
  if (/(docx|word|surat|makalah|proposal|dokumen word)/i.test(p)) return 'docx';
  if (/(xlsx|excel|spreadsheet|tabel data|table data)/i.test(p)) return 'xlsx';
  if (/(website|landing page|web|html|css|javascript|portfolio|fullstack|frontend)/i.test(p)) return 'website';
  return null;
}

function textToTitle(prompt, fallback = 'KelNara Output') {
  const cleaned = String(prompt || '').replace(/\s+/g, ' ').trim();
  if (!cleaned) return fallback;
  return cleaned.slice(0, 70);
}

function splitSections(text) {
  const raw = String(text || '').trim();
  if (!raw) return ['Konten belum tersedia.'];
  return raw.split(/\n{2,}/).map((x) => x.trim()).filter(Boolean).slice(0, 12);
}

function buildWebsiteFiles(prompt, aiText, dir) {
  const title = textToTitle(prompt, 'KelNara Website');
  const sections = splitSections(aiText);
  const htmlSections = sections.map((s, i) => {
    const h = i === 0 ? 'Tentang Project' : `Bagian ${i + 1}`;
    return `<section class="card"><h2>${escapeHtml(h)}</h2><p>${escapeHtml(s)}</p></section>`;
  }).join('\n');

  const index = `<!doctype html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header class="hero">
    <nav>
      <strong>KelNara</strong>
      <a href="#content">Lihat Konten</a>
    </nav>
    <div class="hero-content">
      <p class="badge">Generated by KelNara AI</p>
      <h1>${escapeHtml(title)}</h1>
      <p>Website ini dibuat otomatis berdasarkan permintaan user.</p>
      <a class="button" href="#content">Mulai</a>
    </div>
  </header>
  <main id="content" class="container">
    ${htmlSections}
  </main>
  <footer>© KelNara AI</footer>
  <script src="script.js"></script>
</body>
</html>`;

  const css = `*{box-sizing:border-box}body{margin:0;font-family:Arial,system-ui,sans-serif;background:#f6f7fb;color:#172033;line-height:1.6}.hero{min-height:70vh;padding:24px;background:linear-gradient(135deg,#151b2e,#4056d6);color:#fff}nav{display:flex;justify-content:space-between;align-items:center;max-width:1100px;margin:auto}nav a{color:#fff;text-decoration:none}.hero-content{max-width:900px;margin:120px auto 0}.badge{display:inline-block;background:rgba(255,255,255,.15);padding:8px 12px;border-radius:999px}.hero h1{font-size:clamp(36px,7vw,72px);line-height:1.05;margin:16px 0}.button{display:inline-block;margin-top:18px;background:#fff;color:#2330a8;text-decoration:none;padding:12px 18px;border-radius:12px;font-weight:700}.container{max-width:1100px;margin:-60px auto 60px;padding:0 20px;display:grid;gap:18px}.card{background:#fff;border-radius:22px;padding:28px;box-shadow:0 18px 45px rgba(20,30,70,.12)}.card h2{margin-top:0}footer{text-align:center;padding:32px;color:#667}`;

  const js = `document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');const el=document.querySelector(id);if(el){e.preventDefault();el.scrollIntoView({behavior:'smooth'});}}));`;

  const readme = `# ${title}\n\nGenerated by KelNara AI.\n\n## File\n\n- index.html\n- style.css\n- script.js\n\nBuka index.html di browser.`;

  fs.writeFileSync(path.join(dir, 'index.html'), index);
  fs.writeFileSync(path.join(dir, 'style.css'), css);
  fs.writeFileSync(path.join(dir, 'script.js'), js);
  fs.writeFileSync(path.join(dir, 'README.md'), readme);
}

function escapeHtml(value) {
  return String(value || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function createPdf(prompt, aiText, outPath) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    doc.pipe(fs.createWriteStream(outPath));
    doc.fontSize(22).text(textToTitle(prompt, 'KelNara PDF'), { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).fillColor('#444').text('Generated by KelNara AI', { align: 'center' });
    doc.moveDown(2);
    doc.fillColor('#111').fontSize(12).text(String(aiText || 'Konten belum tersedia.'), { align: 'left' });
    doc.end();
    doc.on('end', () => resolve(outPath));
    doc.on('finish', () => resolve(outPath));
  });
}

async function createDocx(prompt, aiText, outPath) {
  const sections = splitSections(aiText);
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({ text: textToTitle(prompt, 'KelNara Document'), heading: HeadingLevel.TITLE }),
        new Paragraph({ children: [new TextRun({ text: 'Generated by KelNara AI', italics: true })] }),
        ...sections.map((s) => new Paragraph({ text: s })),
      ],
    }],
  });
  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(outPath, buffer);
  return outPath;
}

async function createPptx(prompt, aiText, outPath) {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = 'KelNara AI';
  pptx.subject = textToTitle(prompt, 'KelNara Presentation');
  pptx.title = textToTitle(prompt, 'KelNara Presentation');
  pptx.company = 'KelNara AI';

  const title = textToTitle(prompt, 'KelNara Presentation');
  const sections = splitSections(aiText).slice(0, 6);

  let slide = pptx.addSlide();
  slide.addText(title, { x: 0.7, y: 1.2, w: 12, h: 0.9, fontSize: 34, bold: true });
  slide.addText('Generated by KelNara AI', { x: 0.75, y: 2.15, w: 11, h: 0.4, fontSize: 14, color: '666666' });

  sections.forEach((section, idx) => {
    const s = pptx.addSlide();
    s.addText(`Slide ${idx + 1}`, { x: 0.65, y: 0.45, w: 12, h: 0.4, fontSize: 14, color: '666666' });
    s.addText(idx === 0 ? title : `Bagian ${idx + 1}`, { x: 0.65, y: 0.9, w: 12, h: 0.6, fontSize: 26, bold: true });
    s.addText(section, { x: 0.75, y: 1.75, w: 11.5, h: 4.5, fontSize: 17, fit: 'shrink', breakLine: false });
  });

  await pptx.writeFile({ fileName: outPath });
  return outPath;
}

async function createXlsx(prompt, aiText, outPath) {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('KelNara');
  sheet.columns = [
    { header: 'No', key: 'no', width: 8 },
    { header: 'Konten', key: 'content', width: 80 },
  ];
  splitSections(aiText).forEach((s, i) => sheet.addRow({ no: i + 1, content: s }));
  sheet.getRow(1).font = { bold: true };
  sheet.getColumn('content').alignment = { wrapText: true, vertical: 'top' };
  await workbook.xlsx.writeFile(outPath);
  return outPath;
}

async function generateArtifact(prompt, aiText) {
  const type = detectArtifactType(prompt);
  if (!type) return null;

  const workDir = makeWorkDir();
  const base = safeName(textToTitle(prompt, 'kelnara-output'));

  if (type === 'website') {
    const projectDir = path.join(workDir, 'website-project');
    fs.mkdirSync(projectDir, { recursive: true });
    buildWebsiteFiles(prompt, aiText, projectDir);
    const zipPath = path.join(workDir, `${base}.zip`);
    await zipFolder(projectDir, zipPath);
    return { type, path: zipPath, name: `${base}.zip` };
  }

  if (type === 'pdf') {
    const outPath = path.join(workDir, `${base}.pdf`);
    await createPdf(prompt, aiText, outPath);
    return { type, path: outPath, name: `${base}.pdf` };
  }

  if (type === 'docx') {
    const outPath = path.join(workDir, `${base}.docx`);
    await createDocx(prompt, aiText, outPath);
    return { type, path: outPath, name: `${base}.docx` };
  }

  if (type === 'pptx') {
    const outPath = path.join(workDir, `${base}.pptx`);
    await createPptx(prompt, aiText, outPath);
    return { type, path: outPath, name: `${base}.pptx` };
  }

  if (type === 'xlsx') {
    const outPath = path.join(workDir, `${base}.xlsx`);
    await createXlsx(prompt, aiText, outPath);
    return { type, path: outPath, name: `${base}.xlsx` };
  }

  return null;
}

module.exports = { generateArtifact, detectArtifactType };
